CREATE TABLE roles (
    roles_id INT UNSIGNED NOT NULL UNIQUE PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    deleted_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- CONSTRAINT fk_roles_deleted_by FOREIGN KEY (deleted_by) REFERENCES accounts(accounts_id)
);