ALTER TABLE departments AUTO_INCREMENT = 1;

ALTER TABLE majors AUTO_INCREMENT = 1;

ALTER TABLE student_classes AUTO_INCREMENT = 1;

ALTER TABLE teachers AUTO_INCREMENT = 1;

ALTER TABLE students AUTO_INCREMENT = 1;

ALTER TABLE academic_terms AUTO_INCREMENT = 1;

ALTER TABLE rooms AUTO_INCREMENT = 1;

ALTER TABLE subjects AUTO_INCREMENT = 1;

ALTER TABLE teaching AUTO_INCREMENT = 1;

ALTER TABLE class_sections AUTO_INCREMENT = 1;

ALTER TABLE class_schedules AUTO_INCREMENT = 1;

ALTER TABLE enrollments AUTO_INCREMENT = 1;

ALTER TABLE grade_components AUTO_INCREMENT = 1;

ALTER TABLE assessment_weights AUTO_INCREMENT = 1;

ALTER TABLE payments AUTO_INCREMENT = 1;

ALTER TABLE audit_logs AUTO_INCREMENT = 1;

ALTER TABLE accounts AUTO_INCREMENT = 1;
